import type { Strings } from './strings';

// English. Same shape as the Spanish dictionary in strings.ts: TypeScript flags any missing key.
export const en: Strings = {
  appName: 'Atril',
  close: 'Close',
  cancel: 'Cancel',
  save: 'Save',
  delete: 'Delete',
  add: 'Add',
  done: 'Done',
  nav: { sections: 'Sections', library: 'Library', lists: 'Setlists', settings: 'Settings' },
  library: {
    title: 'Library',
    search: 'Search',
    searchPlaceholder: 'Search title or composer',
    sortRecent: 'Recent',
    sortAz: 'A-Z',
    sort: 'Sort',
    import: 'Import PDF',
    importing: (done: number, total: number) => `Importing ${done} of ${total}…`,
    imported: (added: number, dup: number, relinked: number, errors: number) =>
      [
        added && `${added} imported`,
        relinked && `${relinked} relinked`,
        dup && `${dup} already in the library`,
        errors && `${errors} failed`,
      ]
        .filter(Boolean)
        .join(' · ') || 'Nothing to import',
    scores: 'Scores',
    empty: 'No scores yet. Import your PDFs to get started.',
    noResults: 'No scores match your search.',
    missingPdf: 'PDF missing',
    edit: (title: string) => `Edit ${title}`,
    pin: (title: string) => `Star ${title}`,
    pinned: 'Starred',
    others: 'All scores',
  },
  tags: {
    all: 'All',
    new: 'New tag',
    edit: 'Edit tags',
    rename: (name: string) => `Name of tag ${name}`,
    namePlaceholder: 'Tag name',
    delete: (name: string) => `Delete tag ${name}`,
    confirmDelete: (name: string) => `Delete the tag "${name}"? The scores are kept.`,
  },
  meta: {
    title: 'Score details',
    name: 'Title',
    composer: 'Composer',
    key: 'Key',
    keyPlaceholder: 'F major',
    bpm: 'BPM',
    timeSignature: 'Time signature',
    startNotes: 'Starting notes',
    startNotesHint: 'Per voice (S: F4, A: C4, T: A3, B: F3) or as a chord (F3 A3 C4)',
    tags: 'Tags',
    delete: 'Delete score',
    confirmDelete: (title: string) =>
      `Delete "${title}"? Its annotations are deleted too. This can't be undone.`,
    exportTitle: 'Print or share',
    export: 'Export PDF with annotations',
    exporting: 'Building the PDF…',
    exportHint:
      'Builds a PDF with the original score and, on top, what you drew, highlighted and wrote, plus the symbols you placed. Bookmarks and jumps are left out, and cropping and page order are not applied: every page goes in, in its original order.',
    exportError: "Couldn't build the PDF. Try again.",
    exportMissing: "This score's PDF is missing: import it again from the library.",
    exportSuffix: '(annotated)',
  },
  reader: {
    back: 'Library',
    backToList: 'Setlist',
    page: 'Page',
    fit: 'Page fit',
    more: 'More options',
    readingShort: 'Reading',
    pageMenu: 'Crop and page order',
    bookmarks: 'Bookmarks',
    exportHint: 'Only drawings, text and symbols',
    practice: 'Practice',
    loading: 'Opening…',
    missingPdf: "This score's PDF is missing. Import it again from the library.",
    notFound: 'This score no longer exists.',
    openFailed: "Couldn't open the score.",
    retry: 'Retry',
    settings: 'Reading settings',
    pages: 'Pages',
    annotate: 'Annotate',
    startNote: 'Pitch',
    pageOf: (n: number, total: number) => `page ${n} of ${total}`,
  },
  lists: {
    title: 'Setlists',
    all: 'All setlists',
    new: 'New',
    newName: 'New setlist',
    newTitle: 'New setlist',
    create: 'Create',
    duplicateTitle: 'Duplicate setlist',
    date: 'Date',
    today: 'Today',
    tags: 'Tags',
    allTags: 'All',
    search: 'Search setlist',
    from: 'From',
    to: 'To',
    clearDates: 'Clear dates',
    noDate: 'No date',
    worksColumn: 'Pieces',
    noResults: 'No setlists match the filters.',
    works: (n: number) => `${n} ${n === 1 ? 'piece' : 'pieces'}`,
    empty: 'No setlists yet. Create one to plan a concert or a rehearsal.',
    count: (scores: number, breaks: number) =>
      `${scores} ${scores === 1 ? 'piece' : 'pieces'}` +
      (breaks ? ` and ${breaks === 1 ? 'a break' : `${breaks} breaks`}` : ''),
    name: 'Setlist name',
    notes: 'Notes',
    duplicate: 'Duplicate',
    copySuffix: '(copy)',
    show: 'Show mode',
    dndTitle: 'Before you start',
    dnd: 'Turn on "Do Not Disturb" on your phone: Atril can\'t silence notifications.',
    dndHow: 'How to do it',
    dndOff: "Don't remind me again",
    dndStart: 'Start',
    newTag: 'New tag',
    newTagName: 'Name of the new tag',
    dndAndroid:
      'Android: swipe down from the top and tap "Do Not Disturb". On Xiaomi, also turn off floating notifications.',
    dndIos:
      'iPhone and iPad: Control Center → Focus → Do Not Disturb. With Shortcuts → Automation → "When app is opened" it can turn on by itself when you open Atril.',
    order: 'Order',
    orderLabel: 'Setlist order',
    addScores: 'Add scores',
    addBreak: 'Add break',
    addOne: (title: string) => `Add ${title}`,
    addAgain: 'Again',
    breakLabel: 'Intermission',
    breakName: 'Break name',
    emptyList: 'This setlist is empty. Add scores from the library.',
    move: (name: string) => `Move ${name}`,
    remove: (name: string) => `Remove ${name}`,
    missingScore: 'Deleted score',
    delete: 'Delete setlist',
    confirmDelete: (name: string) => `Delete the setlist "${name}"? The scores are kept.`,
    workOf: (n: number, total: number) => `piece ${n} of ${total}`,
    next: 'Next',
    nextWork: 'Next piece',
    after: (what: string) => `Next up: ${what}`,
    continue: 'Continue',
    endOfList: 'End of setlist',
    unlock: 'Tools locked · tap to use them',
    index: 'Setlist contents',
    backToList: 'Setlist',
  },
  annotate: {
    layer: 'Annotations',
    toolbar: 'Annotation tools',
    tools: {
      pen: 'Pen',
      highlighter: 'Highlighter',
      text: 'Text',
      eraser: 'Eraser',
      stamp: 'Symbols',
    },
    symbols: 'Music symbols',
    symbolsHint:
      'Pick a symbol and tap where it goes. Drag it to move it. Change its size with the line width.',
    groups: {
      notes: 'Notes',
      rests: 'Rests',
      accidentals: 'Accidentals',
      dynamics: 'Dynamics',
      articulations: 'Articulations',
    },
    symbolNames: {
      noteWhole: 'Whole note',
      noteHalfUp: 'Half note',
      noteQuarterUp: 'Quarter note',
      note8thUp: 'Eighth note',
      note16thUp: 'Sixteenth note',
      restWhole: 'Whole rest',
      restHalf: 'Half rest',
      restQuarter: 'Quarter rest',
      rest8th: 'Eighth rest',
      rest16th: 'Sixteenth rest',
      accidentalSharp: 'Sharp',
      accidentalFlat: 'Flat',
      accidentalNatural: 'Natural',
      dynamicPP: 'Pianissimo (pp)',
      dynamicPiano: 'Piano (p)',
      dynamicMP: 'Mezzo piano (mp)',
      dynamicMF: 'Mezzo forte (mf)',
      dynamicForte: 'Forte (f)',
      dynamicFF: 'Fortissimo (ff)',
      fermataAbove: 'Fermata',
      articAccentAbove: 'Accent',
      articStaccatoAbove: 'Staccato',
      breathMarkComma: 'Breath mark',
    },
    color: 'Color',
    colors: ['Black', 'Red', 'Blue', 'Green', 'Yellow'],
    width: 'Width',
    widths: ['Thin', 'Medium', 'Thick'],
    style: 'Color and width',
    undo: 'Undo',
    redo: 'Redo',
    textPlaceholder: 'Write a note',
    show: 'Show annotations',
    hide: 'Hide annotations',
  },
  reading: {
    title: 'Reading settings',
    applyTo: 'Apply to',
    thisScore: 'This score',
    allScores: 'All scores',
    mode: 'Mode',
    paged: 'Paged',
    vertical: 'Vertical',
    twoUp: 'Two pages',
    twoUpStep: 'Advance by',
    stepOne: 'One page',
    stepTwo: 'Two pages',
    pageTurn: 'Page turn',
    slide: 'Slide like paper',
    instant: 'Instant',
    fit: 'Fit',
    fitWidth: 'Fit width',
    fitPage: 'Whole page',
    theme: 'Theme',
    light: 'Light',
    sepia: 'Sepia',
    dark: 'Dark',
    halfPage: 'Half-page turn',
    halfPageHint: 'Shows the top half of the next page before turning',
    tapZones: 'Tap zones',
    thirds: 'Thirds',
    thirdsHint: 'the center shows the bars',
    halves: 'Halves',
    halvesHint: 'long press for the bars',
    autoscrollSpeed: 'Autoscroll speed',
    autoscrollHint: 'Saved for this score. Start autoscroll from the bottom bar.',
  },
  page: {
    title: 'Page',
    pageOrder: 'Page order',
    pageOrderHint: (n: number) =>
      `Repeat or reorder pages without changing the PDF, for example 1, 2, 3, 2, 3, 4. The PDF has ${n}.`,
    crop: 'Crop margins',
    cropHint: 'Trims the white edges so the music looks bigger.',
    percent: (n: number) => `${n}%`,
    cropAuto: 'Automatic',
    cropReset: 'Remove crop',
    cropSides: { top: 'Top', bottom: 'Bottom', left: 'Left', right: 'Right' },
    showAnnotations: 'Show annotations',
    autoscroll: 'Autoscroll',
    autoscrollOn: 'Autoscroll · tap to pause',
  },
  bookmarks: {
    title: 'Bookmarks and jumps',
    bookmarks: 'Bookmarks',
    add: 'Add bookmark',
    placeBookmark: 'Tap the spot on the score you want to mark',
    placeLabel: 'Choose the spot on the page',
    nameTitle: 'Bookmark name',
    name: 'Bookmark name',
    placeholder: 'Letter B, bar 42…',
    empty: 'Mark a spot in the score (for example, where letter B starts) to jump there.',
    page: (page: number) => `p. ${page}`,
    pageLong: (page: number) => `page ${page}`,
    pageShort: (page: number) => `p. ${page}`,
    delete: (label: string) => `Delete bookmark ${label}`,
    jumps: 'Jumps',
    jumpsHint: 'For D.S., coda or repeats: tapping the source on the score jumps to the target.',
    jumpItem: (from: number, target: string) => `From page ${from} to ${target}`,
    deleteJump: (from: number, target: string) => `Delete jump from page ${from} to ${target}`,
    addJump: 'Add jump',
    placeJump: 'Tap the spot on the score to jump from',
    jumpTarget: 'Jump target',
    toBookmark: 'To a bookmark',
    jumpToBookmark: (label: string) => `Target: ${label}`,
    toPage: (n: number) => `To a page (1 to ${n})`,
    jumpTo: (target: string) => `Jump to ${target}`,
  },
  practice: {
    title: 'Practice tools',
    close: 'Close tools',
    metronome: 'Metronome',
    savedTempo: 'Tempo saved for this score',
    bpm: 'BPM',
    tempo: 'Tempo',
    slower: 'Slower',
    faster: 'Faster',
    signature: 'Time signature',
    tap: 'Tap',
    start: 'Start',
    stop: 'Stop',
    beatOf: (n: number, total: number) => `Beat ${n} of ${total}`,
    keyboard: 'Keyboard',
    keyboardLabel: 'Two-octave keyboard',
    octaveDown: 'Octave down',
    octaveUp: 'Octave up',
    range: (from: string, to: string) => `${from} to ${to}`,
    sharp: (name: string, octave: number) => `${name} sharp ${octave}`,
    startNotes: 'Starting notes',
    record: 'Record with the keyboard',
    recordAgain: 'Change',
    recordHint: 'Play the keys in the order you want to give the notes',
    clearStartNotes: 'Clear',
    sustain: 'Pedal',
    sustainHint: 'With the pedal on, the note keeps sounding after you release the key',
    volume: 'Keyboard volume',
    volumeShort: 'Volume',
  },
  backup: {
    title: 'Backup',
    intro:
      'Your scores and annotations live only on this device. Save a backup so you don’t lose them and to move them to another device.',
    last: (when: string) => `Last backup: ${when}.`,
    never: "You haven't made a backup yet.",
    exportAll: 'Export everything (.atril)',
    exportLight: 'Export light',
    lightHint:
      'The light backup leaves out the PDFs: it’s small and easy to send over WhatsApp. After importing it, each score relinks to its PDF when you import that PDF again.',
    import: 'Import backup',
    working: 'Working…',
    exported: 'Backup exported.',
    imported: (scores: number, pending: number) =>
      `Backup imported: ${scores} ${scores === 1 ? 'score' : 'scores'}` +
      (pending ? `. ${pending} still need their PDF: import them again.` : '.'),
    badFile: "That file isn't an Atril backup.",
    failed: "Couldn't finish. Try again.",
    reminder:
      "It's been over a week without a backup. Save one so you don't lose your annotations.",
    sidebarTitle: 'Backup',
    sidebarExport: 'Export file',
    sidebarNever: 'No backup yet',
    sidebarLast: (when: string) => `Saved ${when}`,
  },
  drive: {
    title: 'Google Drive backup',
    sidebarTitle: 'Drive backup',
    intro:
      'Optional. Connect your own Google Drive and the light backup uploads by itself after every change, to an "Atril" folder. Atril can only see the files it created.',
    notConfigured:
      'Not available in this installation: the Google client is not configured (VITE_GOOGLE_CLIENT_ID).',
    connect: 'Connect Google Drive',
    reconnect: 'Reconnect',
    disconnect: 'Disconnect',
    uploadNow: 'Upload now',
    uploaded: 'Backup uploaded to Drive.',
    restore: 'Restore from Drive',
    restoreThis: 'Restore',
    pick: 'Backups in Drive',
    noBackups: 'No backups in the Atril folder yet.',
    lastUpload: (when: string) => `Last upload: ${when}.`,
    connectedNoUpload: 'Connected. No backup uploaded yet.',
    needsReconnect: 'Your Google session expired. Tap Reconnect to keep uploading.',
    uploadFailed: 'The last upload failed. It will retry with the next change.',
    failed: "Couldn't finish. Check your connection and try again.",
  },
  install: {
    title: 'Install Atril',
    installed: 'Atril is installed on this device and works offline.',
    why: 'Installed, Atril opens full screen, works offline and keeps your scores safer.',
    install: 'Install',
    iosSteps: [
      'Open Atril in Safari.',
      'Tap the Share button (the square with the up arrow).',
      'Choose "Add to Home Screen" and confirm.',
      "Open Atril from the new icon and import your scores there: the installed app doesn't share its data with Safari.",
    ],
    other: 'In the browser menu, choose "Install app" or "Add to Home screen".',
    banner: 'Install Atril before importing scores, so they are saved in the app.',
    dismiss: 'Close install notice',
  },
  update: {
    title: 'Version',
    available: 'A new version of Atril is available.',
    apply: 'Update',
    later: 'Later',
    version: (version: string, date: string, sha: string) =>
      `Atril ${version} · released ${date}${sha === 'local' ? '' : ` · ${sha}`}`,
    upToDate:
      'Atril checks for new versions by itself when you open it. If there is one, it tells you here and in the library.',
    check: 'Check for updates',
    checking: 'Checking…',
    latest: "You're on the latest version.",
    found: 'A new version is available: it’s downloading and "Update" will show up in a moment.',
    offline: "Couldn't check: check your connection.",
  },
  settings: {
    title: 'Settings',
    language: 'Language',
    languageAuto: 'Automatic',
    languageHint: (device: string) =>
      `Automatic follows your device’s language (now ${device}). Atril reopens when you change it.`,
    languageNames: { es: 'Español', en: 'English' },
    notationNames: { solfege: 'Do Re Mi', letters: 'C D E' },
    notation: 'Note names',
    notationHint:
      'How notes show on the keyboard and in starting notes. You can type either one. Atril reopens when you change it.',
  },
  hints: {
    done: 'Got it',
    reader: {
      title: 'How to read',
      back: 'Previous page',
      bars: 'Bars and options',
      barsLong: 'Long press: bars and options',
      next: 'Next page',
      text: 'Pinch to zoom; while zoomed, tapping a side still turns the page. In ⋯ (More options) choose Whole page or Fit width; the check mark shows which one is on. A Bluetooth pedal turns pages too.',
    },
    annotate: {
      title: 'Annotate',
      text: 'One finger or the pencil draws. Two fingers move the page and zoom; a two-finger tap without moving undoes. Color, width and symbols are in the bar.',
    },
    markers: {
      title: 'Bookmarks and jumps',
      text: 'A bookmark saves a spot in the score so you can go back there. A jump is a button on the page that takes you to another page or a bookmark: handy for D.S., coda and repeats. To create one, tap Add and then the exact spot on the page.',
    },
    page: {
      title: 'Crop and order',
      text: 'Crop the margins so the music looks bigger; "Automatic" does it for you. In Page order you can repeat pages: "1, 2, 3, 2, 3" reads pages 2 and 3 twice, without flipping back and forth.',
    },
    practice: {
      title: 'Practice',
      text: 'Metronome and keyboard: a note sounds while you hold the key, and with "Pedal" it keeps sounding after you let go. Record the piece’s starting notes with the keyboard and then play them with one tap from the bar.',
    },
    lists: {
      title: 'Setlists and show mode',
      text: 'A setlist is the running order of a concert: give it a date and tags, add scores and breaks, and drag them by the dots. Upcoming ones are at the top; filter by name, tag or dates. "Duplicate" copies the setlist for another day. Show mode steps through it with taps.',
    },
    library: {
      title: 'Your library',
      text: 'Import your PDFs with Import PDF. Tap the star to star a score: starred scores always come first. The three dots open its details: key, BPM, tags and more.',
    },
    backup: {
      title: 'Backup',
      text: 'Your scores live on this device: back up often. Connect Google Drive to save automatically, or export a file. The light backup leaves out the PDFs and is easy to send over WhatsApp.',
    },
  },
  help: {
    title: 'How to use',
    intro: 'Choose what you want to see: we take you there and show it to you in place.',
    cardText: 'The tips for each part of the app, to see them again whenever you want.',
    open: 'See how to use it',
    show: 'Show me',
    showOne: (title: string) => `Show me: ${title}`,
    needScore: 'To see this, import a score first.',
    reset: 'Show all tips again',
    resetDone: 'Done: the tips will show up again.',
  },
};
