// Todos los textos de la interfaz viven acá, listos para traducir.
export const t = {
  appName: 'Atril',
  close: 'Cerrar',
  cancel: 'Cancelar',
  save: 'Guardar',
  delete: 'Eliminar',
  add: 'Agregar',
  done: 'Listo',
  nav: { sections: 'Secciones', library: 'Biblioteca', lists: 'Listas', settings: 'Ajustes' },
  library: {
    title: 'Biblioteca',
    search: 'Buscar',
    searchPlaceholder: 'Buscar título o compositor',
    sortRecent: 'Recientes',
    sortAz: 'A-Z',
    sort: 'Orden',
    import: 'Importar PDF',
    importing: (done: number, total: number) => `Importando ${done} de ${total}…`,
    imported: (added: number, dup: number, relinked: number, errors: number) =>
      [
        added && `${added} ${added === 1 ? 'importada' : 'importadas'}`,
        relinked && `${relinked} ${relinked === 1 ? 'reenganchada' : 'reenganchadas'}`,
        dup && `${dup} ya ${dup === 1 ? 'estaba' : 'estaban'}`,
        errors && `${errors} con error`,
      ]
        .filter(Boolean)
        .join(' · ') || 'Nada para importar',
    scores: 'Partituras',
    empty: 'Todavía no hay partituras. Importá tus PDFs para empezar.',
    noResults: 'Ninguna partitura coincide con la búsqueda.',
    missingPdf: 'Falta el PDF',
    edit: (title: string) => `Editar ${title}`,
  },
  tags: {
    title: 'Etiquetas',
    all: 'Todas',
    new: 'Nueva etiqueta',
    edit: 'Editar etiquetas',
    rename: (name: string) => `Nombre de la etiqueta ${name}`,
    namePlaceholder: 'Nombre de la etiqueta',
    delete: (name: string) => `Eliminar etiqueta ${name}`,
    confirmDelete: (name: string) =>
      `¿Eliminar la etiqueta "${name}"? Las partituras no se borran.`,
  },
  meta: {
    title: 'Datos de la partitura',
    name: 'Título',
    composer: 'Compositor',
    key: 'Tonalidad',
    keyPlaceholder: 'Fa M',
    bpm: 'BPM',
    timeSignature: 'Compás',
    startNotes: 'Notas de inicio',
    startNotesHint: 'Por voz (S: Fa4, A: Do4, T: La3, B: Fa3) o como acorde (Fa3 La3 Do4)',
    tags: 'Etiquetas',
    delete: 'Eliminar partitura',
    confirmDelete: (title: string) =>
      `¿Eliminar "${title}"? Se borran también sus anotaciones. No se puede deshacer.`,
  },
  reader: {
    back: 'Biblioteca',
    backToList: 'Lista',
    page: 'Página',
    fit: 'Ajuste de página',
    practice: 'Ensayo',
    loading: 'Abriendo…',
    missingPdf: 'Falta el PDF de esta partitura. Importalo de nuevo desde la biblioteca.',
    notFound: 'Esta partitura ya no existe.',
    settings: 'Ajustes de lectura',
    pages: 'Páginas',
    annotate: 'Anotar',
    startNote: 'Nota',
    pageOf: (n: number, total: number) => `página ${n} de ${total}`,
  },
  lists: {
    title: 'Listas',
    all: 'Todas las listas',
    new: 'Nueva',
    newName: 'Lista nueva',
    newTitle: 'Nueva lista',
    create: 'Crear',
    empty: 'Todavía no hay listas. Creá una para armar un concierto o un ensayo.',
    count: (scores: number, breaks: number) =>
      `${scores} ${scores === 1 ? 'obra' : 'obras'}` +
      (breaks ? ` y ${breaks === 1 ? 'un separador' : `${breaks} separadores`}` : ''),
    name: 'Nombre de la lista',
    notes: 'Notas',
    duplicate: 'Duplicar',
    copySuffix: '(copia)',
    show: 'Modo show',
    order: 'Orden',
    orderLabel: 'Orden de la lista',
    addScores: 'Agregar partituras',
    addBreak: 'Agregar separador',
    addOne: (title: string) => `Agregar ${title}`,
    addAgain: 'Otra vez',
    breakLabel: 'Intervalo',
    breakName: 'Nombre del separador',
    emptyList: 'La lista está vacía. Agregá partituras de la biblioteca.',
    move: (name: string) => `Mover ${name}`,
    remove: (name: string) => `Quitar ${name}`,
    itemNote: (name: string) => `Nota para ${name}`,
    itemNotePlaceholder: 'Nota',
    missingScore: 'Partitura eliminada',
    delete: 'Eliminar lista',
    confirmDelete: (name: string) => `¿Eliminar la lista "${name}"? Las partituras no se borran.`,
    workOf: (n: number, total: number) => `obra ${n} de ${total}`,
    next: 'Siguiente',
    nextWork: 'Obra siguiente',
    after: (what: string) => `Después, ${what}`,
    continue: 'Seguir',
    endOfList: 'Fin de la lista',
    unlock: 'Herramientas bloqueadas · tocá para usarlas',
    index: 'Índice de la lista',
    backToList: 'Lista',
  },
  annotate: {
    layer: 'Anotaciones',
    toolbar: 'Herramientas de anotación',
    tools: {
      pen: 'Lápiz',
      highlighter: 'Resaltador',
      text: 'Texto',
      eraser: 'Goma',
      stamp: 'Símbolos',
    },
    symbols: 'Símbolos musicales',
    symbolsHint:
      'Elegí un símbolo y tocá donde va. Para moverlo, arrastralo. El tamaño se cambia con el grosor.',
    groups: {
      notes: 'Figuras',
      rests: 'Silencios',
      accidentals: 'Alteraciones',
      dynamics: 'Dinámicas',
      articulations: 'Articulaciones',
    },
    symbolNames: {
      noteWhole: 'Redonda',
      noteHalfUp: 'Blanca',
      noteQuarterUp: 'Negra',
      note8thUp: 'Corchea',
      note16thUp: 'Semicorchea',
      restWhole: 'Silencio de redonda',
      restHalf: 'Silencio de blanca',
      restQuarter: 'Silencio de negra',
      rest8th: 'Silencio de corchea',
      rest16th: 'Silencio de semicorchea',
      accidentalSharp: 'Sostenido',
      accidentalFlat: 'Bemol',
      accidentalNatural: 'Becuadro',
      dynamicPP: 'Pianissimo (pp)',
      dynamicPiano: 'Piano (p)',
      dynamicMP: 'Mezzo piano (mp)',
      dynamicMF: 'Mezzo forte (mf)',
      dynamicForte: 'Forte (f)',
      dynamicFF: 'Fortissimo (ff)',
      fermataAbove: 'Calderón',
      articAccentAbove: 'Acento',
      articStaccatoAbove: 'Staccato',
      breathMarkComma: 'Respiración',
    },
    color: 'Color',
    colors: ['Negro', 'Rojo', 'Azul', 'Verde', 'Amarillo'],
    width: 'Grosor',
    widths: ['Fino', 'Medio', 'Grueso'],
    style: 'Color y grosor',
    undo: 'Deshacer',
    redo: 'Rehacer',
    textPlaceholder: 'Escribí una nota',
    show: 'Mostrar anotaciones',
    hide: 'Ocultar anotaciones',
  },
  reading: {
    title: 'Ajustes de lectura',
    applyTo: 'Aplicar a',
    thisScore: 'Esta partitura',
    allScores: 'Todas las partituras',
    mode: 'Modo',
    paged: 'Paginado',
    vertical: 'Vertical',
    twoUp: 'Dos páginas',
    twoUpStep: 'Avanzar de a',
    stepOne: 'Una página',
    stepTwo: 'Dos páginas',
    pageTurn: 'Al pasar página',
    slide: 'Deslizar como hoja',
    instant: 'Instantáneo',
    fit: 'Ajuste',
    fitWidth: 'Al ancho',
    fitPage: 'Página entera',
    theme: 'Tema',
    light: 'Claro',
    sepia: 'Sepia',
    dark: 'Oscuro',
    halfPage: 'Media página',
    halfPageHint: 'Muestra arriba la mitad de la página siguiente antes de pasar',
    tapZones: 'Zonas de toque',
    thirds: 'Tercios',
    thirdsHint: 'el centro muestra las barras',
    halves: 'Mitades',
    halvesHint: 'barras con toque largo',
    autoscrollSpeed: 'Velocidad del autoscroll',
    autoscrollHint: 'Se guarda en esta partitura. El autoscroll se inicia desde la barra de abajo.',
  },
  page: {
    title: 'Página',
    pageOrder: 'Orden de páginas',
    pageOrderHint: (n: number) =>
      `Repetí o reordená páginas sin tocar el PDF, por ejemplo 1, 2, 3, 2, 3, 4. El PDF tiene ${n}.`,
    crop: 'Recorte de márgenes',
    cropHint: 'Saca el blanco de los bordes para que la música se vea más grande.',
    percent: (n: number) => `${n} %`,
    cropAuto: 'Automático',
    cropReset: 'Quitar recorte',
    cropSides: { top: 'Arriba', bottom: 'Abajo', left: 'Izquierda', right: 'Derecha' },
    showAnnotations: 'Mostrar anotaciones',
    autoscroll: 'Autoscroll',
    autoscrollOn: 'Autoscroll · tocá para pausar',
  },
  bookmarks: {
    title: 'Marcadores y saltos',
    bookmarks: 'Marcadores',
    add: 'Agregar marcador',
    placeBookmark: 'Tocá en la partitura el lugar que querés marcar',
    placeLabel: 'Elegir el lugar en la página',
    nameTitle: 'Nombre del marcador',
    name: 'Nombre del marcador',
    placeholder: 'Letra B, compás 42…',
    empty:
      'Marcá un lugar de la partitura (por ejemplo, donde arranca la letra B) para saltar ahí.',
    page: (page: number) => `pág. ${page}`,
    pageLong: (page: number) => `página ${page}`,
    pageShort: (page: number) => `p. ${page}`,
    delete: (label: string) => `Eliminar marcador ${label}`,
    jumps: 'Saltos',
    jumpsHint: 'Para D.S., coda o repeticiones: tocar el origen en la partitura salta al destino.',
    jumpItem: (from: number, target: string) => `De la página ${from} a ${target}`,
    deleteJump: (from: number, target: string) => `Eliminar salto de la página ${from} a ${target}`,
    addJump: 'Agregar salto',
    placeJump: 'Tocá en la partitura el lugar desde donde se salta',
    jumpTarget: 'Destino del salto',
    toBookmark: 'A un marcador',
    jumpToBookmark: (label: string) => `Destino: ${label}`,
    toPage: (n: number) => `A una página (1 a ${n})`,
    jumpTo: (target: string) => `Saltar a ${target}`,
    jumpBack: 'Volver',
    jumped: (target: string) => `Saltaste a ${target}`,
  },
  practice: {
    title: 'Herramientas de ensayo',
    close: 'Cerrar herramientas',
    metronome: 'Metrónomo',
    savedTempo: 'Tempo guardado en esta partitura',
    bpm: 'BPM',
    tempo: 'Tempo',
    slower: 'Bajar tempo',
    faster: 'Subir tempo',
    signature: 'Compás',
    tap: 'Tap',
    start: 'Iniciar',
    stop: 'Detener',
    beatOf: (n: number, total: number) => `Tiempo ${n} de ${total}`,
    keyboard: 'Teclado',
    keyboardLabel: 'Teclado de dos octavas',
    octaveDown: 'Bajar una octava',
    octaveUp: 'Subir una octava',
    range: (from: string, to: string) => `${from} a ${to}`,
    sharp: (name: string, octave: number) => `${name} sostenido ${octave}`,
    startNotes: 'Notas de inicio',
    record: 'Grabar con el teclado',
    recordAgain: 'Cambiar',
    recordHint: 'Tocá las teclas en el orden en que querés dar las notas',
    clearStartNotes: 'Borrar',
  },
  backup: {
    title: 'Backup',
    intro:
      'Tus partituras y anotaciones viven solo en este dispositivo. Guardá un backup para no perderlas y para pasarlas a otro dispositivo.',
    last: (when: string) => `Último backup: ${when}.`,
    never: 'Todavía no hiciste ningún backup.',
    exportAll: 'Exportar todo (.atril)',
    exportLight: 'Exportar liviano',
    lightHint:
      'El liviano no lleva los PDFs: pesa poco y sirve para mandar por WhatsApp. Al importarlo, cada partitura se reengancha con su PDF cuando lo volvés a importar.',
    import: 'Importar backup',
    working: 'Trabajando…',
    exported: 'Backup exportado.',
    imported: (scores: number, pending: number) =>
      `Backup importado: ${scores} ${scores === 1 ? 'partitura' : 'partituras'}` +
      (pending ? `. A ${pending} les falta el PDF: importalos de nuevo.` : '.'),
    badFile: 'Ese archivo no es un backup de Atril.',
    failed: 'No se pudo completar. Probá de nuevo.',
    reminder: 'Pasó más de una semana sin backup. Guardá uno para no perder tus anotaciones.',
    sidebarTitle: 'Backup',
    sidebarExport: 'Exportar archivo',
    sidebarNever: 'Sin backup todavía',
    sidebarLast: (when: string) => `Guardado ${when}`,
  },
  drive: {
    title: 'Backup en Google Drive',
    sidebarTitle: 'Backup en Drive',
    intro:
      'Opcional. Conectá tu propio Google Drive y el backup liviano se sube solo después de cada cambio, a una carpeta "Atril". Atril solo puede ver los archivos que creó.',
    notConfigured:
      'No disponible en esta instalación: falta configurar el cliente de Google (VITE_GOOGLE_CLIENT_ID).',
    connect: 'Conectar Google Drive',
    reconnect: 'Reconectar',
    disconnect: 'Desconectar',
    uploadNow: 'Subir ahora',
    uploaded: 'Backup subido a Drive.',
    restore: 'Restaurar desde Drive',
    restoreThis: 'Restaurar',
    pick: 'Backups en Drive',
    noBackups: 'Todavía no hay backups en la carpeta Atril.',
    lastUpload: (when: string) => `Última subida: ${when}.`,
    connectedNoUpload: 'Conectado. Todavía no se subió ningún backup.',
    needsReconnect: 'La sesión de Google venció. Tocá Reconectar para seguir subiendo.',
    uploadFailed: 'La última subida falló. Se reintenta con el próximo cambio.',
    failed: 'No se pudo completar. Revisá la conexión y probá de nuevo.',
  },
  install: {
    title: 'Instalar Atril',
    installed: 'Atril está instalada en este dispositivo y funciona sin conexión.',
    why: 'Instalada, Atril abre a pantalla completa, funciona sin conexión y guarda mejor tus partituras.',
    install: 'Instalar',
    iosSteps: [
      'Abrí Atril en Safari.',
      'Tocá el botón Compartir (el cuadrado con la flecha hacia arriba).',
      'Elegí "Agregar a inicio" y confirmá.',
      'Abrí Atril desde el ícono nuevo e importá ahí tus partituras: la app instalada no comparte lo guardado con Safari.',
    ],
    other: 'En el menú del navegador elegí "Instalar app" o "Agregar a la pantalla de inicio".',
    banner: 'Instalá Atril antes de importar partituras: así quedan guardadas en la app.',
    dismiss: 'Cerrar aviso de instalación',
  },
  update: {
    title: 'Versión',
    available: 'Hay una versión nueva de Atril.',
    apply: 'Actualizar',
    later: 'Más tarde',
    version: (version: string, date: string, sha: string) =>
      `Atril ${version} · publicada el ${date}${sha === 'local' ? '' : ` · ${sha}`}`,
    upToDate:
      'Atril busca versiones nuevas sola al abrirla. Si hay una, te avisa acá y en la biblioteca.',
  },
  settings: {
    title: 'Ajustes',
  },
};
